deployment:
  tasks:
    - export DEPLOYPATH=/home/idnafevn
    - /bin/mkdir -p $DEPLOYPATH
    - |
      for d in *.idnads.pro; do
        if [ -d "$d" ]; then
          /bin/mkdir -p "$DEPLOYPATH/$d"
          /usr/bin/rsync -a --delete "$d/" "$DEPLOYPATH/$d/"
        fi
      done
