deployment:
  tasks:
    - export FXPATH=/home/idnafevn/fx.idnads.pro
    - export TRADEPATH=/home/idnafevn/tradecenter.idnads.pro
    - /bin/mkdir -p $FXPATH $TRADEPATH
    - /usr/bin/rsync -a --delete --exclude 'data/' --exclude 'config.php' --exclude 'secret.txt' fx.idnads.pro/ $FXPATH/
    - /usr/bin/rsync -a --delete --exclude 'config.php' --exclude 'secret.txt' tradecenter.idnads.pro/ $TRADEPATH/
